version: 0.2

env:
  variables:
    REACT_APP_API_URL: "http://k8s-default-fortunec-xxxxxxxxxx.$AWS_DEFAULT_REGION.elb.amazonaws.com"
    EKS_CLUSTER_NAME: "eks-cdk-lab"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g npm@latest
      - npm install -g serve
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/fortunecookie/frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm install
      - echo Building React app...
      - npm run build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"react-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - echo Deploying to EKS...
      - kubectl apply -f kubernetes/deployment-react.yaml
      - kubectl apply -f kubernetes/service-react.yaml

artifacts:
  files: imagedefinitions.json

cache:
  paths:
    - 'node_modules/**/*'  # caching for build performance