spring.application.name=fortunecookie
spring.data.mongodb.uri=mongodb://dev:dev-password@localhost:27017/dev

cors.allowed.url=${CORS_ALLOWED_URL:http://localhost:3000}
logging.level.root=INFO
logging.level.com.example.fortunecookie=DEBUG

aws.xray.enabled=false
