---
apiVersion: v1
kind: Service
metadata:
  name: fortune-cookie-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  selector:
    app: fortune-cookie-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000