aws.account.id=${CDK_DEFAULT_ACCOUNT}
aws.region.id=${CDK_DEFAULT_REGION}

# EKS control plane configuration
eks.cluster.name=eks-cdk-lab
eks.kubernetes.version=1.29
eks.controlplane.privateaccess=false
eks.controlplane.publicaccess=true
# EKS control plane logging
eks.controlplane.logging.enabled=true
eks.controlplane.logging.apiserver=true
eks.controlplane.logging.audit=false
eks.controlplane.logging.kcm=true
eks.controlplane.logging.scheduler=true
eks.controlplane.logging.authenticator=true

# Admin IAM access entries
eks.admin.role=arn:aws:iam::${CDK_DEFAULT_ACCOUNT}:role/Admin

# Nodegroup
eks.nodegroup.instance.type=t3.medium
eks.nodegroup.desired=5
eks.nodegroup.min=0
eks.nodegroup.max=15
eks.nodegroup.remote.access.key=hyunkey

# Add-on configuration
eks.managed.addon.enabled=true

eks.managed.addon.vpccni.enabled=true
eks.managed.addon.vpccni.version=v1.18.3-eksbuild.2

eks.managed.addon.kubeproxy.enabled=true
eks.managed.addon.kubeproxy.version=v1.29.7-eksbuild.2

eks.managed.addon.coredns.enabled=true
eks.managed.addon.coredns.version=v1.11.1-eksbuild.11

aws.loadbalancer.controller.enabled=true
aws.loadbalancer.controller.version=v2.6.2

ebs.csi.driver.enabled=true
ebs.csi.driver.version=v1.33.0-eksbuild.1

efs.csi.driver.enabled=false
efs.csi.driver.version=v2.0.7-eksbuild.1

eks.kubecost.enabled=true
eks.kubecost.version=v2.1.0-eksbuild.1

# Cluster Scaling (Node Scaling)
scaling.karpenter.enabled=false
scaling.karpenter.helm.namespace=karpenter
scaling.karpenter.helm.version=
scaling.karpenter.helm.repo=https://charts.karpenter.sh/
scaling.karpenter.irsa=true
scaling.karpenter.serviceaccount=karpenter

scaling.clusterautoscaler.enabled=true
scaling.clusterautoscaler.helm.version=9.37.0
scaling.clusterautoscaler.helm.repo=https://kubernetes.github.io/autoscaler
scaling.clusterautoscaler.helm.namespace=kube-system
scaling.clusterautoscaler.irsa=true
scaling.clusterautoscaler.serviceaccount=cluster-autoscaler

# Monitoring
eks.container.insights.enabled=true
eks.container.insights.irsa=true

kubernetes.kubeopsview.enabled=true
kubernetes.kubeopsview.helm.version=3.5.1
kubernetes.kubeopsview.helm.repo=https://charts.christianhuth.de
kubernetes.kubeopsview.helm.namespace=kube-system

kubernetes.prometheus.enabled=true
kubernetes.prometheus.helm.version=
kubernetes.prometheus.helm.repo=https://prometheus-community.github.io/helm-charts
kubernetes.prometheus.helm.namespace=prometheus

kubernetes.grafana.enabled=true
kubernetes.grafana.helm.version=
kubernetes.grafana.helm.repo=https://grafana.github.io/helm-charts
kubernetes.grafana.helm.namespace=prometheus
kubernetes.grafana.helm.adminPassword=${GRAFANA_ADMIN_PASSWORD}

kubernetes.aws.xray.enabled=false
kubernetes.aws.xray.helm.repo=https://okgolove.github.io/helm-charts/
kubernetes.aws.xray.helm.namespace=xray