package com.myorg.eks.iam;

import software.amazon.awscdk.CfnJson;
import software.amazon.awscdk.Stack;
import software.amazon.awscdk.services.iam.FederatedPrincipal;
import software.amazon.awscdk.services.iam.IOpenIdConnectProvider;

import java.util.Map;

/**
 * This class is responsible for generating trust relationship policies
 * with federated principals using an OIDC provider.
 *
 *        The format of trust relationship policy for the federated principal generated by oidc provider
 *        {
 *             "Effect": "Allow",
 *             "Principal": {
 *                 "Federated": "arn:aws:iam::ACCOUNTID:oidc-provider/oidc.eks.REGION.amazonaws.com/id/72C9E3XXXXXXXXXXXXXX"
 *             },
 *             "Action": "sts:AssumeRoleWithWebIdentity",
 *             "Condition": {
 *                 "StringEquals": {
 *                     "oidc.eks.REGION.amazonaws.com/id/72C9E3XXXXXXXXXXXXXX:aud": "sts.amazonaws.com",
 *                     "oidc.eks.REGION.amazonaws.com/id/72C9E3XXXXXXXXXXXXXX:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
 *                 }
 *         }
 */
public class OIDCTrustPolicyMapper {

    /**
     * Creates a Federated Principal with a condition for a specific service account.
     *
     * @param openIdConnectProvider the OIDC provider to use
     * @param namespace the Kubernetes namespace of the service account
     * @param serviceAccountName the name of the service account
     * @return a FederatedPrincipal configured for the specified service account
     */
    public FederatedPrincipal createFederatedPrincipalWithSubject(IOpenIdConnectProvider openIdConnectProvider, String namespace, String serviceAccountName) {

        // Retrieve the stack context for creating CfnJson
        Stack stack = Stack.of(openIdConnectProvider);

        // Extract the OIDC issuer host
        String oidcIssuerHost = extractOIDCIssuerHost(openIdConnectProvider);

        // Construct a CfnJson for the condition
        CfnJson conditionJson = CfnJson.Builder.create(stack, "ConditionJson"+serviceAccountName)
                .value(Map.of(
                        oidcIssuerHost + ":aud", "sts.amazonaws.com",
                        oidcIssuerHost + ":sub", "system:serviceaccount:" + namespace + ":" + serviceAccountName
                ))
                .build();

        // Return the Federated Principal with the specified condition
        return new FederatedPrincipal(
                openIdConnectProvider.getOpenIdConnectProviderArn(),
                Map.of("StringEquals", conditionJson),
                "sts:AssumeRoleWithWebIdentity"
        );
    }

    /**
     * Creates a Federated Principal with a condition for multiple service accounts.
     *
     * @param openIdConnectProvider the OIDC provider to use
     * @param service the service to create the principal for
     * @return a FederatedPrincipal configured for the specified service
     */
    public FederatedPrincipal createFederatedPrincipalForMultipleServiceAccounts(IOpenIdConnectProvider openIdConnectProvider, String service) {

        // Retrieve the stack context for creating CfnJson
        Stack stack = Stack.of(openIdConnectProvider);

        // Extract the OIDC issuer host
        String oidcIssuerHost = extractOIDCIssuerHost(openIdConnectProvider);

        // Construct a CfnJson for the condition
        CfnJson conditionJson = CfnJson.Builder.create(stack, "ConditionJson"+service)
                .value(Map.of(
                        oidcIssuerHost + ":aud", "sts.amazonaws.com"
                ))
                .build();

        // Return the Federated Principal with the specified condition
        return new FederatedPrincipal(
                openIdConnectProvider.getOpenIdConnectProviderArn(),
                Map.of("StringEquals", conditionJson),
                "sts:AssumeRoleWithWebIdentity"
        );
    }

    /**
     * Extracts the OIDC issuer host from the OpenID Connect provider.
     *
     * @param openIdConnectProvider the OIDC provider
     * @return the OIDC issuer host string
     */
    public String extractOIDCIssuerHost(IOpenIdConnectProvider openIdConnectProvider) {
        return openIdConnectProvider.getOpenIdConnectProviderIssuer().replaceFirst("https://", "");
    }
}
